### ISSUE TITLE
Make logout redirect relative

### ISSUE THREAD

**Issue by TechnikEmpire** [TechnikEmpire/CitadelManager#10]
Logout redirect takes you back to the domain root. Not necessarily desirable because not necessarily where app is installed.

**Comment by dkwiebe** [comment]
@TechnikEmpire It could just redirect you to config('app.url');

**Comment by TechnikEmpire** [comment]
@dkwiebe Ok, will look into it after. I'm working on getting UI/engine/buildbot updates pushed now. Just needed critical stuff fixed so I can get to that point.

**Comment by TechnikEmpire** [comment]
@dkwiebe Thanks for the pointer on this one.
